package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"errors"
	"fmt"

	"posts-service/dataloader"  
	"posts-service/internal/model"
	"posts-service/internal/repository"
)

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *model.Comment) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title, content, author string) (*model.Post, error) {
	if title == "" {
		return nil, fmt.Errorf("title cannot be empty")
	}
	if content == "" {
		return nil, fmt.Errorf("content cannot be empty")
	}
	if author == "" {
		return nil, fmt.Errorf("author cannot be empty")
	}

	post := &model.Post{Title: title, Content: content, Author: author}
	if err := r.PostRepo.CreatePost(ctx, post); err != nil {
		return nil, fmt.Errorf("create post: %w", err)
	}
	return post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	if input.Author == "" {
		return nil, fmt.Errorf("author cannot be empty")
	}
	if input.Content == "" {
		return nil, fmt.Errorf("content cannot be empty")
	}

	comment := &model.Comment{
		PostID:   input.PostID,
		ParentID: input.ParentID,
		Author:   input.Author,
		Content:  input.Content,
	}

	created, err := r.CommentRepo.CreateComment(ctx, comment)
	if err != nil {
		var errDisabled *repository.ErrCommentsDisabled
		var errNotFound *repository.ErrPostNotFound
		var errTooLong *repository.ErrCommentTooLong

		switch {
		case errors.As(err, &errDisabled):
			return nil, fmt.Errorf("comments are disabled for this post")
		case errors.As(err, &errNotFound):
			return nil, fmt.Errorf("post not found")
		case errors.As(err, &errTooLong):
			return nil, fmt.Errorf("comment exceeds maximum length of %d characters", errTooLong.MaxLength)
		default:
			return nil, fmt.Errorf("create comment: %w", err)
		}
	}
	return created, nil
}

// ToggleComments is the resolver for the toggleComments field.
func (r *mutationResolver) ToggleComments(ctx context.Context, postID string, allowComments bool) (*model.Post, error) {
	post, err := r.PostRepo.ToggleComments(ctx, postID, allowComments)
	if err != nil {
		var errNotFound *repository.ErrPostNotFound
		if errors.As(err, &errNotFound) {
			return nil, fmt.Errorf("post not found")
		}
		return nil, fmt.Errorf("toggle comments: %w", err)
	}
	return post, nil
}

// Comments is the resolver for the comments field.
func paginateComments(comments []*model.Comment, first *int, after *string) *model.CommentConnection {
	limit := 10
	if first != nil && *first > 0 {
		limit = *first
	}

	start := 0
	if after != nil && *after != "" {
		for i, c := range comments {
			if c.ID == *after {
				start = i + 1
				break
			}
		}
	}

	end := start + limit
	if end > len(comments) {
		end = len(comments)
	}

	pageComments := comments[start:end]
	edges := make([]*model.CommentEdge, len(pageComments))
	for i, c := range pageComments {
		edges[i] = &model.CommentEdge{Node: c, Position: c.ID}
	}

	hasNextPage := end < len(comments)
	var endPosition *string
	if len(edges) > 0 {
		endPosition = &edges[len(edges)-1].Position
	}

	return &model.CommentConnection{
		Edges:      edges,
		PageInfo:   &model.PageInfo{HasNextPage: hasNextPage, EndPosition: endPosition},
		TotalCount: len(comments),
	}
}

func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first *int, after *string) (*model.CommentConnection, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil {
		comments, err := loaders.CommentsByPostID.Load(ctx, obj.ID)
		if err != nil {
			return nil, fmt.Errorf("get comments: %w", err)
		}
		return paginateComments(comments, first, after), nil
	}

	limit := 10
	if first != nil && *first > 0 {
		limit = *first
	}
	conn, err := r.CommentRepo.GetCommentsByPostID(ctx, obj.ID, limit, after)
	if err != nil {
		return nil, fmt.Errorf("get comments: %w", err)
	}
	return conn, nil
}

func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first *int, after *string) (*model.CommentConnection, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil {
		replies, err := loaders.RepliesByParentID.Load(ctx, obj.ID)
		if err != nil {
			return nil, fmt.Errorf("get replies: %w", err)
		}
		return paginateComments(replies, first, after), nil
	}

	limit := 10
	if first != nil && *first > 0 {
		limit = *first
	}
	conn, err := r.CommentRepo.GetRepliesByParentID(ctx, obj.ID, limit, after)
	if err != nil {
		return nil, fmt.Errorf("get replies: %w", err)
	}
	return conn, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *model.Post) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int, after *string) (*model.PostConnection, error) {
	limit := 10
	if first != nil && *first > 0 {
		limit = *first
	}
	conn, err := r.PostRepo.GetPosts(ctx, limit, after)
	if err != nil {
		return nil, fmt.Errorf("get posts: %w", err)
	}
	return conn, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.PostRepo.GetPostByID(ctx, id)
	if err != nil {
		var errNotFound *repository.ErrPostNotFound
		if errors.As(err, &errNotFound) {
			return nil, nil 
		}
		return nil, fmt.Errorf("get post: %w", err)
	}
	return post, nil
}

func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	ch, err := r.CommentRepo.Subscribe(ctx, postID)
	if err != nil {
		return nil, fmt.Errorf("subscribe: %w", err)
	}
	return ch, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }