// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentConnection struct {
	Edges      []*CommentEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type CommentEdge struct {
	Node     *Comment `json:"node"`
	Position string   `json:"position"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Author   string  `json:"author"`
	Content  string  `json:"content"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartPosition   *string `json:"startPosition,omitempty"`
	EndPosition     *string `json:"endPosition,omitempty"`
}

type PostConnection struct {
	Edges      []*PostEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type PostEdge struct {
	Node     *Post  `json:"node"`
	Position string `json:"position"`
}

type Query struct {
}

type Subscription struct {
}
